using UnityEngine;
using UnityEditor;
using UnityEditor.Animations;
using System.IO;
using System.Linq;

public class SpriteAnimationGenerator
{
    [MenuItem("Tools/Generate Sprite Animation")]
    static void GenerateAnimation()
    {
        // Путь к папке со спрайтами
        string spriteFolderPath = "Assets/Sprites/Dance/Legs";

        // Получаем все спрайты
        string[] spriteGuids = AssetDatabase.FindAssets("t:Sprite", new[] { spriteFolderPath });
        Sprite[] sprites = spriteGuids
            .Select(guid => AssetDatabase.LoadAssetAtPath<Sprite>(AssetDatabase.GUIDToAssetPath(guid)))
            .OrderBy(s => s.name) // сортировка по имени
            .ToArray();

        if (sprites.Length == 0)
        {
            Debug.LogWarning("No sprites found in folder: " + spriteFolderPath);
            return;
        }

        // Создание анимации
        AnimationClip clip = new AnimationClip();
        clip.frameRate = 12; // кадров в секунду

        EditorCurveBinding spriteBinding = new EditorCurveBinding
        {
            type = typeof(SpriteRenderer),
            path = "",
            propertyName = "m_Sprite"
        };

        ObjectReferenceKeyframe[] keyFrames = new ObjectReferenceKeyframe[sprites.Length];
        for (int i = 0; i < sprites.Length; i++)
        {
            keyFrames[i] = new ObjectReferenceKeyframe
            {
                time = i / clip.frameRate,
                value = sprites[i]
            };
        }

        AnimationUtility.SetObjectReferenceCurve(clip, spriteBinding, keyFrames);

        // Сохраняем анимацию
        string animPath = spriteFolderPath + "/AutoGenerated.anim";
        AssetDatabase.CreateAsset(clip, animPath);
        AssetDatabase.SaveAssets();

        Debug.Log("Animation created at: " + animPath);

        // 🔄 Применяем к выделенному объекту
        GameObject selected = Selection.activeGameObject;
        if (selected != null)
        {
            Animator animator = selected.GetComponent<Animator>();
            if (!animator)
                animator = selected.AddComponent<Animator>();

            string controllerPath = spriteFolderPath + "/AutoGeneratedController.controller";
            AnimatorController controller = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);
            controller.AddMotion(clip);
            animator.runtimeAnimatorController = controller;

            Debug.Log("Animation and Animator applied to selected object: " + selected.name);
        }
        else
        {
            Debug.LogWarning("No GameObject selected to apply the animation.");
        }
    }
}
